version: '3.8'
services:
  postgressqlalchemy:
    image: postgres
    restart: always
    ports:
      - 9090:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andres.yanquen@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - postgressqlalchemy
